# Generated by Django 5.1.7 on 2025-03-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWR', 'Owner'), ('USR', 'User')], default='USR', max_length=3)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6)),
                ('age', models.IntegerField()),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('picture_profile', models.URLField()),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
    ]
