# Generated by Django 5.1.7 on 2025-03-23 02:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='genre',
            new_name='gender',
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('rooms', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_type', models.CharField(choices=[('MXN', 'Mxn'), ('USD', 'Usd'), ('EUR', 'Eur')], default='MXN', max_length=3)),
                ('period', models.CharField(max_length=30)),
                ('availability', models.BooleanField(default=True)),
                ('reserved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='RentalHistory',
            fields=[
                ('rent_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('review', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('property_rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
