# Generated by Django 5.1.7 on 2025-03-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
