# Generated by Django 5.1.7 on 2025-03-23 15:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_genre_user_gender_alter_user_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalhistory',
            name='property_rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_history', to='api.property'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
